# Generated by Django 6.0.3 on 2026-04-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='requirement',
            new_name='machine_requirement',
        ),
        migrations.AddField(
            model_name='lead',
            name='is_popup_submitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='raw_material_requirement',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='main.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_id',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
